### ISSUE TITLE
Need support for Wisconsin state road format

### ISSUE THREAD

**Issue by drw2074** [TheCre8r/WME-Road-Shield-Helper#1]
Wisconsin uses WIS-XXX format instead of SR-XXX. Shield exists. (wxw777 WI SM)

**Comment by TheCre8r** [comment]
Thank you. I should have an update coming out today or tomorrow. Can you please give me a PL to test?

**Comment by drw2074** [comment]
Here's a  for testing. [https://www.waze.com/en-US/editor?env=usa&lon=-89.79950&lat=44.02543&zoom=2&segments=77305591](url)

wxw777
