### ISSUE TITLE
CH/CR Shield should be available in Illinois

### ISSUE THREAD

**Issue by ehepner1977** [TheCre8r/WME-Road-Shield-Helper#12]
Illinois uses CH-xx to designate roads that should have the generic CR- hexagonal shield.

**Comment by TheCre8r** [comment]
I should be able to get to that today.

**Comment by TheCre8r** [comment]
Working in the beta version. Should be released very soon.

**Comment by TheCre8r** [comment]
I haven't forgot about you. I am adding a few more states in the group and then it will be pushed out. Thank you for your patience.

**Comment by ehepner1977** [comment]
It's almost as if you have a life outside Waze or something. Probably shouldn't let Mrs. Cre8r know this she might expect you to help or something.
