### ISSUE TITLE
SR-xxx in Ohio defaults to generic state shield

### ISSUE THREAD

**Issue by ldriveskier** [TheCre8r/WME-Road-Shield-Helper#15]
When using the autofill in Ohio for state routes, the shield defaults to the generic state main shield instead of the Ohio shield. Is it possible to also check the state field when the name starts with SR- and autofill the Ohio shield instead? Thanks!

**Comment by sethspeedy28** [comment]
This has been fixed in a beta version. Update should be out soon.
