### ISSUE TITLE
California uses SR-

### ISSUE THREAD

**Issue by eeffaann** [TheCre8r/WME-Road-Shield-Helper#16]
California uses SR-, please add to the default shields list.

**Comment by sethspeedy28** [comment]
Autofill in the Shields panel pulls the SR Generic Main, when it should pull the CA State Main.

**Comment by sethspeedy28** [comment]
PL for testing: https://waze.com/en-US/editor?env=usa&lat=35.26676&lon=-119.02240&marker=true&zoom=5&segments=6574525

**Comment by TheCre8r** [comment]
Working in Beta, should be released to public soon.
