### ISSUE TITLE
Mississippi: Shield not Supported

### ISSUE THREAD

**Issue by sethspeedy28** [TheCre8r/WME-Road-Shield-Helper#23]
Mississippi uses the SR Generic Main shield. The script throws this error:

"Error: MS Road Shield is not available."

Nothing autofills. Mississippi uses the "MS-xxx" format. PL: https://www.waze.com/en-US/editor?env=usa&lat=32.33647&lon=-89.48362&marker=true&zoom=5&segments=510491139

**Comment by TheCre8r** [comment]
Working in latest beta, will be pushed to production soon.

**Comment by jm6087** [comment]
Looks good - close
