### ISSUE TITLE
New Jersey: Shield not Supported

### ISSUE THREAD

**Issue by sethspeedy28** [TheCre8r/WME-Road-Shield-Helper#24]
New Jersey uses the SR Generic Main shield. The script throws the following error:

"Error: SR Road Shield is not available."

Nothing autofills. New Jersey uses the "SR-xxx" format. PL: https://www.waze.com/en-US/editor?env=usa&lat=40.24673&lon=-74.29383&marker=true&zoom=5&segments=31893332

**Comment by TheCre8r** [comment]
Working in beta, should be released to production soon.

**Comment by jm6087** [comment]
Looks good - close
