### ISSUE TITLE
New Mexico: Incorrect Shield

### ISSUE THREAD

**Issue by sethspeedy28** [TheCre8r/WME-Road-Shield-Helper#25]
New Mexico uses the New Mexico - State Main shield. The script currently fills the SR Generic Main shield and gives the following warning:

"Warning: State Shield Not Verified. Consult local guidance and Report an Issue on GitHub"

PL https://www.waze.com/en-US/editor?env=usa&lat=34.25246&lon=-105.59511&marker=true&zoom=6&segments=33433017

Correct shield verified with mhh60(NM SM)

**Comment by TheCre8r** [comment]
Working in beta, should be released to production soon.

**Comment by jm6087** [comment]
Confirmed, working
