### ISSUE TITLE
Feature Request - Turn Guidance Preview

### ISSUE THREAD

**Issue by s18slider** [TheCre8r/WME-Road-Shield-Helper#28]
Add a Turn Guidance Preview when moussing over a turn arrow to show Turn Guidance without having to go into the edit window.
<img width="395" alt="Example" src="https://user-images.githubusercontent.com/17627625/124854896-1a946580-df76-11eb-9ed8-692339a6e93b.PNG">

**Comment by TheCre8r** [comment]
Good idea. I'll see what I can do.

**Comment by skykep** [comment]
and maybe a little indication to show whether the TTS is native or overridden

**Comment by TheCre8r** [comment]
Added in fe01e63946a0a79574455763f0f59020df436986
