### ISSUE TITLE
Error when pressing Autofill on Wisconsin county roads

### ISSUE THREAD

**Issue by drw2074** [TheCre8r/WME-Road-Shield-Helper#3]
Wisconsin has the format of CH-XX where XX is on or two letters. Getting an error when running Autofill. Always reproducible. Debug image attached.  Sample PL:  [https://www.waze.com/en-US/editor?env=usa&lon=-91.94968&lat=44.91929&zoom=3&segments=56500836](url)

![2021-05-31_10-51-39](https://user-images.githubusercontent.com/46326552/120217944-ad671500-c1fe-11eb-996b-d052214bb61a.jpg)

**Comment by TheCre8r** [comment]
Thank you for the report.  This should be fixed in the first release in June.
