### ISSUE TITLE
Option for whether to display "Buttons" popup

### ISSUE THREAD

**Issue by Harmonious4** [TheCre8r/WME-Road-Shield-Helper#30]
Since small caps, », and • are (unfortunately) only allowed in the USA, the buttons to add them are unnecessary for editors outside the USA. An option to suppress display of the popup would reduce screen clutter.

**Comment by TheCre8r** [comment]
Good idea. Do you believe it will be better to hide them in the settings tab, or in the Turn Instructions dialog?

**Comment by Harmonious4** [comment]
I think the settings tab, just another checkbox under "Filter shields by state"
