### ISSUE TITLE
Road direction not shown in preview when shield is added in the toward section

### ISSUE THREAD

**Issue by williamholden98** [TheCre8r/WME-Road-Shield-Helper#36]
![Screenshot (210)](https://user-images.githubusercontent.com/88698610/128804749-3670eb5f-f80d-4712-8feb-8d72240bb1a0.png)

URL to location of attached screenshot in WME: https://www.waze.com/en-US/editor?env=usa&lon=-81.98374&lat=34.97512&zoom=6&segments=44218047

**Comment by williamholden98** [comment]
Example of this issue as shown in the attached screenshot is available here: https://www.waze.com/en-US/editor?env=usa&lon=-81.98374&lat=34.97512&zoom=6&segments=44218047

**Comment by Harmonious4** [comment]
Can you just copy `${Shield.direction ? Shield.direction : ''}` from line 658 down to the corresponding part of line 672 to fix this issue? Seems to work for me.
