### ISSUE TITLE
tryScan  error

### ISSUE THREAD

**Issue by eric215** [TheCre8r/WME-Road-Shield-Helper#37]
Error -- <<TypeError : cannot read property 'getAttribute' of null>> 

RSH version 2021.08.09.01
WME - prod
Chrome - prod

How to recreate:  select any segment, pan the edit window around a bit and then hit the soft refresh.  Results in  this error 100% of time.  It is not necessary to have edit changes pending.
![Capture](https://user-images.githubusercontent.com/13973937/130520355-2f59c0c7-e065-40a2-bbe5-5859b4b51bea.JPG)

**Comment by TheCre8r** [comment]
I believe this is an issue with Road Shield Assistant.

**Comment by eric215** [comment]
Yes -- this is an RSA issue, closing this defect
