### ISSUE TITLE
Add Canadian logic for Road Shield Buttons

### ISSUE THREAD

**Issue by TheCre8r** [TheCre8r/WME-Road-Shield-Helper#41]
The Canadian champs have decided that we're going to use small caps after all, but our BGS put the text in all small caps, rather than the first letter being larger (ɴᴏʀᴛʜ instead of Nᴏʀᴛʜ). Would it be possible for you to have the RSH script use this format for the buttons in Canada? We would want buttons for », ɴᴏʀᴛʜ, ꜱᴏᴜᴛʜ, ᴇᴀꜱᴛ, ᴡᴇꜱᴛ, ɴᴏʀᴅ, ꜱᴜᴅ, ᴇꜱᴛ, and ᴏᴜᴇꜱᴛ.

**Comment by Harmonious4** [comment]
A related minor issue that was pointed out by Webs101 is that the turn instruction preview should say "XXX m" rather than "XXX feet" in Canada. The • button may also occasionally get used
