### ISSUE TITLE
RSH Preview is not showing directions in towards field.

### ISSUE THREAD

**Issue by theRadison** [TheCre8r/WME-Road-Shield-Helper#46]
RSH Preview is not showing directions in towards field.

Examples:
https://www.waze.com/en-US/editor?env=usa&lon=-95.72377&lat=34.92571&zoomLevel=18&segments=39838807
[US-270][SH-1 Eᴀꜱᴛ] shield in the towards field only displays [US-270][SH-1] shield in preview. Expected to see [US-270] [SH-1 Eᴀꜱᴛ] with brackets representing equivalent shields.

https://www.waze.com/en-US/editor?env=usa&lon=-95.72366&lat=34.92453&zoomLevel=18&segments=39828897
[SH-31 Eᴀꜱᴛ] shield only displaying [SH-31]

**Comment by jm6087** [comment]
This should be working in the production version.  I just submitted a PR to fix it in the Nightly version

**Comment by jm6087** [comment]
Nightly updated with fix.
