### ISSUE TITLE
Missouri Supplemental Shields

### ISSUE THREAD

**Issue by theRadison** [TheCre8r/WME-Road-Shield-Helper#8]
Missouri uses SH-xx to designate Supplemental Shields.  MO-xx is used for primary state highways.  
Supplemental routes are also entirely lettered routes.

**Comment by TheCre8r** [comment]
Resolved in Version 2021.06.05.01 https://github.com/TheCre8r/WME-Road-Shield-Helper/commit/7d3c3160258eeaac01c003f7576ec06d1c421456
