### ISSUE TITLE
Arkansas Suffix Shields

### ISSUE THREAD

**Issue by theRadison** [TheCre8r/WME-Road-Shield-Helper#9]
Arkansas is unique when it comes to "bannered" routes such as BUS and SPUR.  Instead of using a traditional shield, such as US-xx BUS, they instead add a suffix.  

A road named US-71 BUS will instead carry a shield of US-71B.  Same for AR-255 SPUR, it would be AR-255S.

In practice, Arkansas will never have a US-xx BUS or US-xx SPUR shield utilized.  (BYPASS is used)

**Comment by TheCre8r** [comment]
Can you please provide a PL to test?

**Comment by theRadison** [comment]
Here is a PL with both (US-412 BUS and AR-295 SPUR)
https://www.waze.com/en-US/editor?env=usa&lon=-93.87012&lat=36.15095&zoom=3&segments=82570845,511737573

**Comment by TheCre8r** [comment]
Working in the beta version. Should be released very soon.
